import mongoose from 'mongoose';

const resourceSchema = mongoose.Schema({
    title: { type: String },
    urls: [String],
    websites: [String],
    files: [{
        filename: String,
        originalName: String,
        mimetype: String,
        size: Number,
        path: String
    }],
    summary: { type: String }, // 2-3 sentence summary generated by LangChain
    description: { type: String }, // Detailed description generated by LangChain/Gemini
    class: { type: mongoose.Schema.Types.ObjectId, ref: 'Class', required: false }, // Can be null for personal
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true } // Track resource owner
});

export default mongoose.model('Resource', resourceSchema);